
metadata = [];
metadata = daff_metadata_addKey(metadata, 'Description', 'String', 'Example directivity');
metadata = daff_metadata_addKey(metadata, 'Temperature_Degree_Celsius', 'Float', 21.3);
metadata = daff_metadata_addKey(metadata, 'Averages', 'Int', 12);
metadata = daff_metadata_addKey(metadata, 'Windowed', 'Bool', false);


daff_write('filename', 'ps.daff',...
           'content', 'ps', ...
           'datafunc', @another_test_callback_function, ... %@dfBulbMS, ...
           'channels', 1, ...
           'alphares', 5, ...
           'betares', 5, ...
           'metadata', metadata, ...
           'orient', [0 0 0])