clc;

% Create the metadata
metadata = [];
metadata = daff_metadata_addKey(metadata, 'Keyname', 'String', 'Tralala');
metadata = daff_metadata_addKey(metadata, 'Lufttemperatur', 'Float', 2.34238);
metadata = daff_metadata_addKey(metadata, 'Zahl', 'Int', 0);
metadata = daff_metadata_addKey(metadata, 'Boolesch', 'Bool', false);
metadata = daff_metadata_addKey(metadata, 'Label_Channel_1', 'String', 'HRIR left ear');
metadata = daff_metadata_addKey(metadata, 'Label_Channel_2', 'String', 'HRIR right ear');

% % Write an impulse response DAFF file
x = daff_write('filename', 'ir.daff',...
           'basepath', 'E:\Temp\Mess04_LautsprecherRaus_Fenster', ...
           'content', 'ir', ...
           'datafunc', @daff_datafunc_example1, ...
           'channels', 2, ...
           'alphares', 1, ...
           'betares', 5, ...
           'mdist', 1.0, ...
           'reference', 72.0, ...
           'orient', [0 0 0], ...
           'metadata', metadata, ...
           'zthreshold', -80);


% Write an magnitude spectrum DAFF file
% x = daff_write('filename', 'ms.daff',...
%                'content', 'ms', ...
%                'datafunc', @daff_datafunc_example2, ...
%                'channels', 1, ...
%                'alphares', 5, ...
%                'betares', 5, ...
%                'mdist', 1.0, ...
%                'reference', 72.0, ...
%                'orient', [0 0 0], ...
%                'metadata', metadata);
