clc;

% Create the metadata
metadata = [];
metadata = daff_metadata_addKey(metadata, 'test_string', 'String', 'Tralala');
metadata = daff_metadata_addKey(metadata, 'test_float', 'Float', pi);
metadata = daff_metadata_addKey(metadata, 'test_int', 'Int', -1);
metadata = daff_metadata_addKey(metadata, 'test_bool', 'Bool', false);

% % Write an impulse response DAFF file
daff_write('filename', 'test_ir.daff',...
           'content', 'ir', ...
           'datafunc', @daff_write_test_ir_datafunc, ...
           'channels', 3, ...
           'alphares', 1, ...
           'betares', 5, ...
           'mdist', 1.0, ...
           'reference', 72.0, ...
           'orient', [0 0 0], ...
           'metadata', metadata, ...
           'zthreshold', -80);


% Write an magnitude spectrum DAFF file
daff_write('filename', 'test_ms.daff',...
               'content', 'ms', ...
               'datafunc', @daff_write_test_ms_datafunc, ...
               'channels', 1, ...
               'alphares', 5, ...
               'betares', 5, ...
               'mdist', 1.0, ...
               'reference', 72.0, ...
               'orient', [0 0 0], ...
               'metadata', metadata);
