
metadata = [];
metadata = daff_metadata_addKey(metadata, 'Description', 'String', 'Example DFT directive');
metadata = daff_metadata_addKey(metadata, 'Function', 'String', 'real: Hamming window, imag: 1=const');


daff_write('filename', 'dft.daff',...
           'content', 'dft', ...
           'datafunc', @dft_test_callback_function, ...
           'channels', 1, ...
           'alphares', 20, ...
           'betares', 20, ...
           'metadata', metadata, ...
           'orient', [0 0 0])
       
h = DAFF('open', 'dft.daff');
x = DAFF('getRecordByIndex', h, 1);
y = complex(x(1:2:length(x)),x(2:2:length(x)));
plot((1:1024), real(y), (1:1024), imag(y));