clc;

metadata = [];
metadata = daff_metadata_addKey(metadata, 'description', 'String', 'This is a test file for debugging. 1°x1° resolution, 360 alpha points, 181 beta points. Impulse response content with minimum filter length 4. First filter value = beta * 1000 + alpha.');

daff_write('filename', 'verify_1x1_orient_0-0-0.daff',...
           'content', 'ir', ...
           'datafunc', @daff_debug_datafunc, ...
           'quantization', 'float32', ...
           'channels', 1, ...
           'alphares', 1, ...
           'betares', 1, ...
           'orient', [0 0 0], ...
           'metadata', metadata, ...
           'quiet');

daff_write('filename', 'verify_1x1_orient_90-0-0.daff',...
           'content', 'ir', ...
           'datafunc', @daff_debug_datafunc, ...
           'quantization', 'float32', ...
           'channels', 1, ...
           'alphares', 1, ...
           'betares', 1, ...
           'orient', [90 0 0], ...
           'metadata', metadata, ...
           'quiet');
       
daff_write('filename', 'verify_1x1_orient_0-90-0.daff',...
           'content', 'ir', ...
           'datafunc', @daff_debug_datafunc, ...
           'quantization', 'float32', ...
           'channels', 1, ...
           'alphares', 1, ...
           'betares', 1, ...
           'orient', [0 90 0], ...
           'metadata', metadata, ...
           'quiet');    
       
daff_write('filename', 'verify_1x1_orient_0-0-90.daff',...
           'content', 'ir', ...
           'datafunc', @daff_debug_datafunc, ...
           'quantization', 'float32', ...
           'channels', 1, ...
           'alphares', 1, ...
           'betares', 1, ...
           'orient', [0 0 90], ...
           'metadata', metadata, ...
           'quiet');       