
metadata = [];
metadata = daff_metadata_addKey(metadata, 'Description', 'String', 'Example directivity');
metadata = daff_metadata_addKey(metadata, 'Temperature_Degree_Celsius', 'Float', 21.3);
metadata = daff_metadata_addKey(metadata, 'Averages', 'Int', 12);
metadata = daff_metadata_addKey(metadata, 'Windowed', 'Bool', false);


daff_write('filename', 'ms.daff',...
           'content', 'ms', ...
           'datafunc', @multichannel_test_callback_function, ... 
           'channels', 3, ...
           'alphares', 5, ...
           'betares', 5, ...
           'mdist', 1.0, ...
           'reference', 72.0, ...
           'orient', [0 0 0], ...
           'metadata', metadata)